### ISSUE TITLE
two step auth

### ISSUE THREAD

**Issue by TrueFalseOrNull** [hjiangsu/thunder#109]
**Description**  
When trying to login in an instance that has two step authentication it won't show a field to add it

**How to Reproduce**  
1. Go to manage accounts
2. Click on add account 
3. Scroll down to  add user, password and Andy instance.
4. See error "missing totp token"

**Expected Behavior**  
show a field to add the token

**Device & App Version:**  
 - OS: [e.g. iOS8.1]  Android 10
 - Version [e.g. 22] v0.2.1+7

**Additional Context**  
there should be a field to add the auth token

**Comment by chenew** [comment]
@TrueFalseOrNull , I also have 2FA enabled on my account. Without a 2FA field, the login fails and I can't get logged in at all. What I ended up doing as a workaround is to temporarily disable 2FA in Lemmy, log in to Thunder, then re-enable 2FA. So far, the apps seems to function properly, but we'll see if the session stays active over the next few days. Hopefully this gets the attention of @hjiangsu as I'd assume this will impact more people since Lemmy introduced 2FA in their latest release.

**Comment by MrAntonS** [comment]
I'm down to work on this feature

**Comment by hjiangsu** [comment]
Yeah, I agree that this is an important feature to add in as soon as possible. @MrAntonS, do you mind if I issue this ticket to you? Thanks!

**Comment by MrAntonS** [comment]
Yes please

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
