### ISSUE TITLE
Highlight own comments

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#175]
**Is your feature request related to a problem? Please describe.**
Make one's own comments easier to spot by highlighting them somehow.

**Describe the solution you'd like**
Highlight your own comments, perhaps by making your own username green?

**Comment by hjiangsu** [comment]
How does this look? I would need to also test it out with other Material You themes if possible, since currently, it just uses a static green colour

![simulator_screenshot_34DE88C3-824E-4D96-A04D-33E137563DCE](https://github.com/hjiangsu/thunder/assets/30667958/01b9667d-558d-40f0-84d4-fa2570cc439a)

**Comment by CTalvio** [comment]
Using the accent colour, would make sense to me. Would make the app feel more cohesive.

**Comment by hjiangsu** [comment]
I've changed it to the following:
- username displays in primary colour, depending on what it is for your material you theme
- for the OP, i've changed it to be the secondary colour
- for admin, I've changed it to the tertiary colour

https://m3.material.io/theme-builder#/custom

**Comment by hjiangsu** [comment]
This has been added in the pre-release version v0.2.1-alpha.1+11. Feel free to test it out and see what you think!

**Comment by CTalvio** [comment]
I'm trying to uninstall the app, and reset everything.

But even if I clear its storage before doing so, when I install it again, and open it for the first time.

I am already logged into my sopuli.xyz account.

**Comment by hjiangsu** [comment]
Hmm, thats weird - I did change the logic a bit in order to accommodate the swipe gesture customizability so I can take a closer look at this

**Comment by CTalvio** [comment]
I figured it out.

I was logged in using my account name, like this: mentaledge

But my display name is: MentalEdge

This broke something, and thunder was unable to tell which comments were mine.

I logged out and back in, this time entering my account name as: MentalEdge

And now it works.

**Comment by hjiangsu** [comment]
Ahhh - okay yeah, I was assuming it had something to do with username/display name thing. I'll try to make it more robust and use the user id rather than username to check if a comment is yours or not

**Comment by machinaeZER0** [comment]
> I've changed it to the following:
> 
>     * username displays in primary colour, depending on what it is for your material you theme
> 
>     * for the OP, i've changed it to be the secondary colour
> 
>     * for admin, I've changed it to the tertiary colour

I like this idea in theory, but an issue I'm seeing (if it's working, which I believe it is) is that certain Material You themes are going to be somewhat muted and/or utilize fairly similar looking colors (at least when it comes to being represented in something small like lettering). Example here of me talking with you in a post you created:
![Screenshot_20230704-222206](https://github.com/hjiangsu/thunder/assets/3624023/249be295-1322-4a7e-bf14-2738930dbecd)

I think when it comes to something like this, it probably makes sense to either use colors that immediately draw the eye (and potentially are consistent regardless of theme choice), or pair these roles (OP/Admin/your own posts) with icons? Or both? It'll be a little less clean, but I think (personally) it would make the most sense to do in this situation. What do you think?

**Comment by machinaeZER0** [comment]
This Jerboa screenshot shows off the use of icons, but also shows off another potential route to go - where material colors might not all stick out when used as the actual font color, making it the background of the username in question actually makes it pop in a big way!
![Screenshot_20230630-074830](https://github.com/hjiangsu/thunder/assets/3624023/37106b4d-480b-4508-b0aa-2e0da3de8aa1)

Maybe this would be worth trying out in some fashion?

**Comment by hjiangsu** [comment]
I think what I can do to keep it cleaner is to add chips as a way to distinguish OP, moderator, and admin statuses. I think icons are nice, but they are often times more distracting and should be used sparingly (similar to avatar or community icons)

However, feel free to let me know otherwise! I'm not a UI/UX designer by any means so maybe someone more knowledgeable than me can chip in (pun totally intended)

This is what I mean by chips: https://m3.material.io/components/chips/guidelines

**Comment by machinaeZER0** [comment]
Hahah, good one 😂 if chips are what they were using in that Jerboa
screenshot I think that's a good experiment!

I love UI/UX and I get to play with it a lot for work, but by no means an
expert. I do think it may be one of those situations though where (as
opposed to something like a FAB, or nav icon color) it can be more helpful
to use a consistent color that catches the eye, so that would be my only
"concern" on the Material You front. That said, if the only people getting
chips are yourself, OPs and admins then it probably won't lead to any crazy
mixups :)

**Comment by CTalvio** [comment]
Dome and released, further discussion on how to distinguish mods and admins can continue here or in a new issue.
