### ISSUE TITLE
Action buttons on post tiles are misaligned

### ISSUE THREAD

**Issue by PcLover2** [hjiangsu/thunder#36]
**Description**  
As you can see the action buttons are not ailgned with the post info view.
![Screenshot_20230621-093340_thunder~2](https://github.com/hjiangsu/thunder/assets/106612743/dd1909ae-135b-4751-abfd-22eea0674249)

**Expected Behavior**  
The buttons should be aligned with the post info
![Adobe_20230621_100016](https://github.com/hjiangsu/thunder/assets/106612743/c90e61f3-e8ea-468f-9a72-a15f0f9fa259)

**Device & App Version:**  
 - Device: Samsung S9
 - OS: Lineageos 20 (Android 13)
 - Version 2.0 alpha

**Additional Context**  
I cannot really code but if you need help with anything UI or UX related i could always give advice.

**Comment by hjiangsu** [comment]
The way it is now, it should be aligned in the center of the community name and the post info. I intentionally made it that way so that the touch target for the actions are larger and easier to interact with!

![image](https://github.com/hjiangsu/thunder/assets/30667958/d517f5e9-d9b2-4872-96f2-a9018b859856)

However, this can very well change depending on community feedback (I'm not too well versed in UX/UX principles so any feedback is good feedback)

Thanks for the suggestion and let me know what you think!

**Comment by PcLover2** [comment]
O alright i didnt notice that, it just seemed so high up in the post tile. Its certainly good enough to stay like that so if you want you can close this issue

**Comment by hjiangsu** [comment]
No worries! Thanks for the feedback regardless and feel free to open up more issues regarding UI/UX flow that you think might be good
